name: Build, Package, and Release React Vite App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '23.10.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run prettier

      - name: Run ESLint check
        run: npm run eslint -- .

      - name: Run build
        run: npm run build-prod

      - name: 📖 Extract Version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Package dist folder
        run: |
          zip -r HappierPath-v${{ env.VERSION }}.zip dist

      - name: 🚀 Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: "HappierPath Release v${{ env.VERSION }}"
          body: "📢 New version v${{ env.VERSION }} of HappierPath 🚀"
          draft: false
          prerelease: false
          files: HappierPath-v${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
