name: Build, Package, and Release HappierPath

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '23.10.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run prettier

      - name: Run ESLint check
        run: npm run lint

      - name: Run build
        run: npm run build-prod

      - name: 📖 Extract Version from manifest.json
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=$(jq -r '.version' dist/manifest.json)
          else
            VERSION="DEV"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: 📦 Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  package:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist

      - name: 📖 Extract Version
        id: extract_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=$(jq -r '.version' dist/manifest.json)
          else
            VERSION="DEV"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Package dist folder
        run: |
          cd dist && zip -r ../HappierPath-v${{ env.VERSION }}.zip .

      - name: 📦 Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: HappierPath-v${{ env.VERSION }}.zip
          path: HappierPath-v${{ env.VERSION }}.zip

  release:
    runs-on: ubuntu-latest
    needs: package
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download packaged artifact
        uses: actions/download-artifact@v4
        with:
          pattern: HappierPath-v*
          merge-multiple: false

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "HappierPath Release ${{ github.ref_name }}"
          body: "📢 New version ${{ github.ref_name }} of HappierPath 🚀"
          draft: false
          prerelease: false
          files: HappierPath-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
